strictness: medium
doc-warnings: true

ignore-paths:
  - cdo_data
  - configs
  - docs
  - functions
  - plot_scripts
  - tests
  - __init__.py
  - LICENSE

pylint:
  disable:
    - logging-format-interpolation  # allow .format in loggers
    - too-many-locals
    - too-many-arguments
    - too-many-statements

pep257:
  disable:
    - D413  # Missing blank line after last section
    - D212  # Multi-line docstring should start at first line (wrong positive?)
    - D213
